### ISSUE TITLE
I1 - Filter Recipes by Tag

### ISSUE THREAD

**Issue by Virulencies** [EGavinG/whats-cookin-team-#4]
Add functionality to filter recipes by their associated tags

**Comment by jamiefrancisco** [comment]
function filterRecipesByTag(recipes, tags) {
  const filteredRecipesByTag = recipes.filter(recipe => {
    const allTagsMatch = tags.every(tag => recipe.tags.includes(tag));
    return allTagsMatch;
  });
  return filteredRecipesByTag;
}
