### ISSUE TITLE
I1 - Filter Recipes by Name

### ISSUE THREAD

**Issue by Virulencies** [EGavinG/whats-cookin-team-#5]
Add functionality to filter and display recipes from the home page by recipe name

**Comment by jamiefrancisco** [comment]
function filterRecipesByName(recipes, name) {
  const filteredRecipesByName = recipes.filter(recipe => {
    const upperCaseRecipeName = recipe.name.toUpperCase();
    return upperCaseRecipeName.includes(name.toUpperCase());
  });
  return filteredRecipesByName;
}
