### ISSUE TITLE
I1 - Function to Calculate Recipe Cost

### ISSUE THREAD

**Issue by Virulencies** [EGavinG/whats-cookin-team-#6]

**Comment by jamiefrancisco** [comment]
function calculateRecipeCost(recipe, ingredientsData) {
  const totalCost = (!recipe || !ingredientsData) ? 0 :
    recipe.ingredients.reduce((acc, ingredient) => {
      const ingredientCost = getIngredientProperty(ingredient.id, ingredientsData, 'estimatedCostInCents');
      return acc + (ingredientCost ? ingredientCost * ingredient.quantity.amount : 0);
    }, 0);

  return (totalCost / 100).toFixed(2);
}
